# Generated by Django 3.0.3 on 2021-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminward', models.CharField(max_length=50)),
                ('councillorward', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('emp_category', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsmBuildings29Oct21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField()),
                ('fid', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('osm_id', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('addrstreet', models.CharField(blank=True, max_length=200, null=True)),
                ('building', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('num_flats', models.BigIntegerField(blank=True, null=True)),
                ('wings', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'osm_buildings_29oct21',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ward61BuildingsOsm2Nov2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('osm_id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=97, null=True)),
                ('addrstreet', models.CharField(blank=True, max_length=91, null=True)),
                ('building', models.CharField(blank=True, max_length=80, null=True)),
                ('roofmateri', models.CharField(blank=True, max_length=80, null=True)),
                ('osmward', models.CharField(blank=True, max_length=100, null=True)),
                ('num_flat', models.IntegerField(blank=True, null=True)),
                ('num_shops', models.IntegerField(blank=True, null=True)),
                ('wing', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ward61_buildings_osm_2nov2021',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteSegregationDetails',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('building_cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('num_wings', models.CharField(blank=True, max_length=100, null=True)),
                ('wing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('building_type', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=100, null=True)),
                ('num_households_premises', models.CharField(blank=True, max_length=100, null=True)),
                ('num_shops_premises', models.CharField(blank=True, max_length=100, null=True)),
                ('type_waste_generator', models.CharField(blank=True, max_length=100, null=True)),
                ('waste_segregation', models.CharField(blank=True, max_length=100, null=True)),
                ('wet_waste_before_segregation', models.CharField(blank=True, max_length=100, null=True)),
                ('dry_waste_before_segregation', models.CharField(blank=True, max_length=100, null=True)),
                ('hazardous_waste', models.CharField(blank=True, max_length=100, null=True)),
                ('compostable_waste', models.CharField(blank=True, max_length=100, null=True)),
                ('recyclable_waste', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_waste', models.CharField(blank=True, max_length=100, null=True)),
                ('composting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('compost_bin_by_mcgm', models.CharField(blank=True, max_length=100, null=True)),
                ('date_notice_issued', models.CharField(blank=True, max_length=100, null=True)),
                ('name_number', models.CharField(blank=True, max_length=100, null=True)),
                ('coll_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waste_segregation_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZerowasteGrievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('grievance', models.TextField()),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'zerowaste_grievance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZerowasteRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('service_swk', models.IntegerField()),
                ('timing_swk', models.IntegerField(blank=True, null=True)),
                ('mobile_swk', models.IntegerField(blank=True, null=True)),
                ('compost_kit_garden', models.IntegerField(blank=True, null=True)),
                ('communicate_swk', models.IntegerField(blank=True, null=True)),
                ('solid_waste_man', models.IntegerField(blank=True, null=True)),
                ('service_workers', models.IntegerField(blank=True, null=True)),
                ('segregation', models.IntegerField(blank=True, null=True)),
                ('recycle_process', models.IntegerField(blank=True, null=True)),
                ('awareness', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'zerowaste_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZerowasteReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_date', models.DateField()),
                ('recyclable_waste', models.FloatField(blank=True, null=True)),
                ('compostable_waste', models.FloatField(blank=True, null=True)),
                ('dry_waste_bf', models.FloatField(blank=True, null=True)),
                ('hazardous_waste', models.FloatField(blank=True, null=True)),
                ('region_name', models.CharField(max_length=100)),
                ('wet_waste_bf', models.FloatField(blank=True, null=True)),
                ('rejected_waste', models.FloatField(blank=True, null=True)),
                ('building_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zerowaste_report',
                'managed': False,
            },
        ),
    ]
